version: '3'

services:

    bot:
      expose:
        - 8000
      ports:
        - 8000:8000
      build:
        context: .
      restart: on-failure
      stop_signal: SIGINT
      depends_on:
        - postgres
    postgres:
      image: postgres:14-alpine
      restart: on-failure
      ports:
        - 6532:6532
      volumes:
        - postgres-data:/var/lib/postgresql/data
      environment:
        POSTGRES_PASSWORD: 
        POSTGRES_USER: 
        POSTGRES_DB: 

volumes:
  postgres-data:
